permalink: pretty

defaults:
    -
        scope:
            path: ""            # everything
            type: "posts"       # but just posts
        values:
            layout: "post"      # use post layout

kramdown:
    auto_ids: false             # stop headers having an id